name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy artifact to release folder
        run: |
          mkdir release
          cd target
            cp target/SpigotPluginGenerator-*.jar ../release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: release