name: Java CI with Maven

on:
  - push


jobs:
  build:



    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: Spigot-Plugin-Generator
          path: target/Spigot-Plugin-Generator.jar